# Generated by Django 3.1.4 on 2020-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covidRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=255)),
                ('recovered', models.CharField(max_length=255)),
                ('new_cases', models.CharField(blank=True, max_length=255, null=True)),
                ('new_deaths', models.CharField(blank=True, max_length=255, null=True)),
                ('total_deaths', models.CharField(blank=True, max_length=255, null=True)),
                ('total_tests', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('latest_update', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'MASTER COVID DATA RECORD',
                'db_table': 'covid_record',
            },
        ),
    ]
